### ISSUE TITLE
Invalid errors

### ISSUE THREAD

**Issue by RaikoKitame** [zaksabeast/Gen-7-GTS-Character-Picture-Freeze-Fix#1]
Hello, 

Trying to apply this on european UltraSun version and I have this : 

PS E:\Téléchargements\Compressed\GTS> ./armips main.s -equ PLAYER_IMAGE_LOCATION 0x3301286c -equ PROCESS_CHARACTER_IMAGE 0x306c38 -equ ERROR_CASE 0x306c64
E:\Téléchargements\Compressed\GTS/main.s(8) error: Undefined label "process_character_image"
E:\Téléchargements\Compressed\GTS/main.s(8) fatal error: Invalid position
E:\Téléchargements\Compressed\GTS/main.s(12) error: Undefined label "error_case"
E:\Téléchargements\Compressed\GTS/main.s(12) error: Invalid expression type
E:\Téléchargements\Compressed\GTS/main.s(17) error: Undefined label "error_case"
E:\Téléchargements\Compressed\GTS/main.s(17) fatal error: Invalid position
E:\Téléchargements\Compressed\GTS/main.s(22) error: Undefined label "process_character_image"
E:\Téléchargements\Compressed\GTS/main.s(22) error: Invalid expression type
E:\Téléchargements\Compressed\GTS/main.s(24) error: Undefined label "player_image_location"
E:\Téléchargements\Compressed\GTS/main.s(24) error: Invalid expression
Aborting.

May you help me please ?

**Comment by zaksabeast** [comment]
Hello!

You can download prebuilt versions from the releases page: https://github.com/zaksabeast/Gen-7-GTS-Character-Picture-Freeze-Fix/releases
