### ISSUE TITLE
Portable to XY/ORAS

### ISSUE THREAD

**Issue by Bappsack** [zaksabeast/Gen-7-GTS-Character-Picture-Freeze-Fix#2]
Is it possible to port this to XY/ORAS aswell?

The same is happening now to the Gen6 GTS, instead of a freeze the 3DS just crashes, its prolly related to the same issue due Character Sprites.

**Comment by zaksabeast** [comment]
Which Pokemon are causing the crash?  I spot checked several, but didn't run into an issue.

**Comment by Bappsack** [comment]
it seems to be related to colored nicknames/Phrases ?, try looking for a machop or legendaries, i send you a friend request on discord for future discussions.

**Comment by zaksabeast** [comment]
Fixed with [cd90b91](https://github.com/zaksabeast/Gen-7-GTS-Character-Picture-Freeze-Fix/commit/cd90b9190ab14480e5864b733f3b690abf004156).
